image: python:latest
pages:
  stage: deploy
  only:
    - main
  script:
    - pip install mkdocs-material
    - pip install python-markdown-math
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
---