# Project information
site_name: 'Logiweb Microservices'
site_description: 'Technical solution description for Logiweb Microservices project.'
site_author: 'Aleksey Tyan'
site_url: 'https://gitlab.com/tuanalexeu/logiweb-microservices/'

# Copyright
copyright: '&copy; 2021 tuanalexeu'

# Repository
repo_name: 'GitLab'
repo_url: 'https://gitlab.com/tuanalexeu/logiweb-microservices/'
edit_uri: 'https://gitlab.com/tuanalexeu/technical-solution-description/-/tree/main/docs'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: '#e20075'
    accent: '#e20075'
  features:
    - tabs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://gitlab.com/tuanalexeu'
    - icon: 'fontawesome/brands/vk'
      link: 'https://vk.com/anonymousmen'

# Page tree
nav:
  - 'Home': 'index.md'
  - 'Microservices':
      - 'Logiweb': 'microservices/logiweb-service.md'
      - 'Dashboard': 'microservices/dashboard-service.md'
      - 'Client Service': 'microservices/client-order-service.md'
      - 'Chat Service': 'microservices/chat-service.md'
      - 'Telegram Bot': 'microservices/telegram-bot-service.md'
      - 'Spring Cloud Config': 'microservices/config-service.md'
  - 'Logging': 'logging.md'
  - 'Testing': 'testing.md'
  - 'MQ Broker': 'messaging.md'
  - 'Deployment':
      - 'GitLab': 'deployment/gitlab.md'
      - 'Docker': 'deployment/docker.md'
      - 'Kubernetes': 'deployment/k8s.md'
      - 'Google Cloud Platform': 'deployment/gcp.md'
      - 'DNS': 'deployment/dns.md'
  - 'Summary': 'summary.md'