apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsd-service
  labels:
    app: tsd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsd-service
  template:
    metadata:
      labels:
        app: tsd-service
    spec:
      containers:
        - name: tsd-service
          image: tuanalexeu/tsd:final-task
          ports:
            - containerPort: 8000